image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache fatJar
  artifacts:
    expire_in: '14 day'
    paths:
    - build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle


verify:
  stage: deploy
  script:
    - java -jar ./build/libs/spottit-0.7.0.jar --help
  except:
    - schedules
    
run:
  stage: deploy
  script:
    - java -jar ./build/libs/spottit-0.7.0.jar -c "${CONFIG_NAME}"
  only:
    - schedules
