image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  VERSION: "0.9.0"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache --no-daemon bootJar
  artifacts:
    expire_in: '14 day'
    paths:
    - build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


test:
  stage: test
  script: gradle check --no-daemon
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  except:
    variables:
      - $CONFIG_FILE


run:
  stage: deploy
  script:
    - java -jar ./build/libs/spottit-${VERSION}.jar -c "${CONFIG_FILE}"
  only:
    variables:
      - $CONFIG_FILE

verify:
  stage: deploy
  script: java -jar ./build/libs/spottit-${VERSION}.jar --help
  except:
    variables:
      - $CONFIG_FILE




