image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache fatJar
  artifacts:
    expire_in: '14 day'
    paths:
    - build/libs/*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


test:
  stage: test
  script: [ -n "$RUN_TEST" ] && gradle check;
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle


run:
  stage: deploy
  script:
    - if [ -n "$CONFIG_FILE" ]; then CONFIG_FILE="-c ${CONFIG_FILE}"; fi
    - ARGS=${CONFIG_FILE:-"--help"}
    - java -jar ./build/libs/spottit-0.7.0.jar ${ARGS}
    

